title: Java PathFinder Documentation
description: JPF is an extensible software model checking framework for Java bytecode programs
baseurl: "/jpf-core"
url: "https://mahmoud-khawaja.github.io"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-relative-links

# Navigation menu
navigation:
  - title: "Home"
    url: "/jpf-core/"
  - title: "Introduction"
    url: "/jpf-core/intro/"
  - title: "Installation"
    url: "/jpf-core/install/"
  - title: "User Guide"
    url: "/jpf-core/user/"
  - title: "JPF Core Project"
    url: "/jpf-core/jpf-core/"
  - title: "Developer Guide"
    url: "/jpf-core/devel/"
  - title: "Google Summer of Code"
    url: "/jpf-core/Google-Summer-of-Code.md"
  - title: "Workshops"
    url: "/jpf-core/JPF-Workshops.md"
  - title: "Projects"
    url: "/jpf-core/projects/"

# Exclude files and folders that shouldn't be processed
exclude:
  - README.md
  - docs/_Sidebar.md
  - docs/_Footer.md
  - docs/graphics
  - docs/Call-for-JPF-*.md
  - docs/Downloading-sources-(OLD).md

# Optional: if you want to customize the permalink style globally
permalink: pretty
