   - name: Checkout GitHub Pages repository
     uses: actions/checkout@v4
     with:
       repository: Mahmoud-Khawaja/Mahmoud-Khawaja.github.io
       token: ${{ secrets.DOCS_PAT }}
       path: target
